"""initial data spine schema

Revision ID: fcf480af6941
Revises: 
Create Date: 2026-07-02 08:03:21.175258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf480af6941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=32), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_direct_spend', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('taxonomy_code')
    )
    op.create_table('demand_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.Enum('LOW', 'BASE', 'HIGH', name='demand_scenario_type'), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('projected_volume_change_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('projected_spend_usd', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('volatility_index', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_agent', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_demand_scenarios_category_id', 'demand_scenarios', ['category_id'], unique=False)
    op.create_index('ix_demand_scenarios_scenario_type', 'demand_scenarios', ['scenario_type'], unique=False)
    op.create_table('market_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('price_index', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('yoy_price_change_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'period_month', 'region', name='uq_market_benchmarks_category_month_region')
    )
    op.create_index('ix_market_benchmarks_category_id', 'market_benchmarks', ['category_id'], unique=False)
    op.create_index('ix_market_benchmarks_period_month', 'market_benchmarks', ['period_month'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('primary_category_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('diversity_flag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_id')
    )
    op.create_index('ix_suppliers_primary_category_id', 'suppliers', ['primary_category_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('negotiated_unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', 'DRAFT', name='contract_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_index('ix_contracts_category_id', 'contracts', ['category_id'], unique=False)
    op.create_index('ix_contracts_status', 'contracts', ['status'], unique=False)
    op.create_index('ix_contracts_supplier_id', 'contracts', ['supplier_id'], unique=False)
    op.create_table('savings_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=64), nullable=False),
    sa.Column('estimated_savings_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED', name='opportunity_status'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source_transaction_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_benchmark_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_agent', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_savings_opportunities_category_id', 'savings_opportunities', ['category_id'], unique=False)
    op.create_index('ix_savings_opportunities_status', 'savings_opportunities', ['status'], unique=False)
    op.create_index('ix_savings_opportunities_supplier_id', 'savings_opportunities', ['supplier_id'], unique=False)
    op.create_table('spend_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('business_unit', sa.String(length=64), nullable=False),
    sa.Column('cost_center', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spend_transactions_category_date', 'spend_transactions', ['category_id', 'transaction_date'], unique=False)
    op.create_index('ix_spend_transactions_category_id', 'spend_transactions', ['category_id'], unique=False)
    op.create_index('ix_spend_transactions_supplier_id', 'spend_transactions', ['supplier_id'], unique=False)
    op.create_index('ix_spend_transactions_transaction_date', 'spend_transactions', ['transaction_date'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('match_status', sa.Enum('MATCHED', 'DISCREPANCY', 'UNMATCHED', name='invoice_match_status'), nullable=False),
    sa.Column('discrepancy_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discrepancy_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['spend_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_contract_id', 'invoices', ['contract_id'], unique=False)
    op.create_index('ix_invoices_match_status', 'invoices', ['match_status'], unique=False)
    op.create_index('ix_invoices_supplier_id', 'invoices', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_supplier_id', table_name='invoices')
    op.drop_index('ix_invoices_match_status', table_name='invoices')
    op.drop_index('ix_invoices_contract_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_spend_transactions_transaction_date', table_name='spend_transactions')
    op.drop_index('ix_spend_transactions_supplier_id', table_name='spend_transactions')
    op.drop_index('ix_spend_transactions_category_id', table_name='spend_transactions')
    op.drop_index('ix_spend_transactions_category_date', table_name='spend_transactions')
    op.drop_table('spend_transactions')
    op.drop_index('ix_savings_opportunities_supplier_id', table_name='savings_opportunities')
    op.drop_index('ix_savings_opportunities_status', table_name='savings_opportunities')
    op.drop_index('ix_savings_opportunities_category_id', table_name='savings_opportunities')
    op.drop_table('savings_opportunities')
    op.drop_index('ix_contracts_supplier_id', table_name='contracts')
    op.drop_index('ix_contracts_status', table_name='contracts')
    op.drop_index('ix_contracts_category_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_suppliers_primary_category_id', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_market_benchmarks_period_month', table_name='market_benchmarks')
    op.drop_index('ix_market_benchmarks_category_id', table_name='market_benchmarks')
    op.drop_table('market_benchmarks')
    op.drop_index('ix_demand_scenarios_scenario_type', table_name='demand_scenarios')
    op.drop_index('ix_demand_scenarios_category_id', table_name='demand_scenarios')
    op.drop_table('demand_scenarios')
    op.drop_table('categories')
    # ### end Alembic commands ###
